image:
  repository: likelion-cr-mh.kr.ncr.ntruss.com/del-app
  pullPolicy: Always
  tag: ""

imagePullSecrets:
  - name: ncpsecret

nameOverride: ""
fullnameOverride: ""

containerPort: 8000

service:
  type: LoadBalancer
  port: 80
  targetPort: 8000

dbService:
  type: NodePort
  port: 5432


autoscaling:
  enabled: true
  minReplicas: 3
  maxReplicas: 100
  targetCPUUtilizationPercentage: 40
  targetMemoryUtilizationPercentage: 50

replicaCount: 3

configMap:
  django:
    DJANGO_SETTINGS_MODULE: "delivery_app.settings.local"