global:
  scrape_interval: 10s
  evaluation_interval: 10s

  external_labels:
    monitor: django-monitor

rule_files:
  - "django.rules"
  
scrape_configs:
  - job_name: "django"
    metrics_path: /metrics
    static_configs:
    - targets: ["del-app:8000"]