# persistance volume claim
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "del.db.fullname" . }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: nks-block-storage