apiVersion: v1
kind: Pod
metadata:
  name: {{ include "del.db.fullname" . }}
  labels:
    app: {{ include "del.db.labels" . | nindent 4}}
spec:
  containers:
    - name: {{ include "del.db.fullname" . }}
      image: postgres:15
      env:
      - name: PGDATA
        value: "var/lib/postgresql/data/separate"
      envFrom:
      - secretRef:
          name: {{ include "del.db.fullname" . }}
      ports: 
        - containerPort: 5432
      volumeMounts:
      - name: postgres-data
        mountPath: "var/lib/postgresql/data"
  volumes:
  - name: postgres-data
    persistentVolumeClaim:
      claimName: {{ include "del.db.fullname" . }}