name: CD

on:
  workflow_dispatch:
  pull_request:
    branches:
      - "main"
    types:
      - closed

env:
  IMAGE: ${{ secrets.NCP_CONTAINER_REGISTRY }}/del-app
  IMAGE_TAG: ${{ secrets.NCP_CONTAINER_REGISTRY }}/del-app:latest

jobs:
  deploy:
    name: deploy new version
    runs-on: ubuntu-latest

    steps:
      - name: Get release version
        id: get_version
        run: |
          echo "$NEW_TAG %TAG"
          echo "TAG=${{ github.event.release.tag_name }}" >> $GITHUB_ENV
      
      - name: Checkout code
        if: ${{ env.TAG != '' }}
        uses: actions/checkout@v3
        with:
          ref: main
          token: ${{ secrets.DEL_APP }}
      
      - name: Get version
        if: startsWith(github.ref, 'refs/tags')
        id: version
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> "$GITHUB_OUTPUT"

      - name: Update appVersion in Chart.yaml
        if: ${{ env.TAG != ''}}
        run: |
          cd helm-chart
          sed -i 's/appVersion: ".*"/appVersion: "${{ steps.version.output.VERSION }}"/g' Chart.yaml

      - name: Commit files
        if: ${{ env.TAG != ''}}
        run: |
          git add .
          git config --local user.email "yaezzin@gmail.com"
          git config --local user.name "github-actions[bot]"
          git commit -a -m "update chart tag"

      - name: Push changes
        if: ${{ env.TAG != ''}}
        uses: ad-m/github-push-action@master
        with:
          branch: main
          github_token: ${{ secrets.DEL_APP }}
