name: CD

on:
  workflow_dispatch:
  pull_request:
    branches:
      - "main"
    types:
      - closed

env:
  IMAGE: ${{ secrets.NCP_CONTAINER_REGISTRY }}/del-app
  IMAGE_TAG: ${{ secrets.NCP_CONTAINER_REGISTRY }}/del-app:latest

jobs:
  deploy:
    name: deploy new version
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: main
          token: ${{ secrets.DEL_APP }}
      
      - name: Get version
        id: version
        run: | 
          echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Update appVersion in Chart.yaml
        if: ${{ env.VERSION != ''}}
        run: |
          sed -ie 's/appVersion: ".*"/appVersion: "'${{ env.VERSION }}'"/g' helm-chart/Chart.yaml

      - name: Commit files
        if: ${{ env.VERSION != ''}}
        run: |
          git add .
          git config --local user.email "yaezzin@gmail.com"
          git config --local user.name "github-actions[bot]"
          git commit -a -m "update chart tag"

      - name: Push changes
        if: ${{ env.VERSION != ''}}
        uses: ad-m/github-push-action@master
        with:
          branch: main
          github_token: ${{ secrets.DEL_APP }}
